security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            access_denied_handler: App\Security\AccessDeniedHandler

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: false
                success_handler: App\Security\LoginSuccessHandler

            logout:
                path: app_logout
                target: app_login
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login$, allow_if: "!is_authenticated()" }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home$, roles: PUBLIC_ACCESS }
        - { path: ^/piano$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }